version: '3.9'

services:
  auth_service:
    build: .
    container_name: auth_service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./auth.db
    volumes:
      - .:/app
    restart: always
